//Autogenerated triple quantized liym file with draw function
int lakeEarstricount = 2;
float lakeEarsvertpos[] = {9.476190, 0.033946, 9.872804, 4.303811, 0.033947, 7.392668, 7.857056, 0.033947, 4.029205, -9.519773, 0.033946, 10.056389, -3.582346, 0.033947, 7.927495, -8.172437, 0.033947, 4.550702};
unsigned char lakeEarsvertcol[] = {35, 35, 35, 19, 19, 19, 24, 24, 24, 35, 35, 35, 19, 19, 19, 24, 24, 24};
